### ISSUE TITLE
23.2.1: `feature_dbcrash.py` failed: `JSONRPCException: bad-txns-in-ne-out, value in != value out (-26)`

### ISSUE THREAD

**Issue by whitslack** [ElementsProject/elements#1297]
**Expected behavior**

All functional tests should pass.

**Actual behavior**

```
3/255 - feature_dbcrash.py failed, Duration: 17 s

stdout:
2023-11-28T19:48:00.719000Z TestFramework (INFO): Initializing test directory /var/tmp/portage/net-p2p/elements-23.2.1/temp/test_runner_₿_🏃_20231128_144755/feature_dbcrash_254
2023-11-28T19:48:16.699000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/var/tmp/portage/net-p2p/elements-23.2.1/work/elements-23.2.1/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/var/tmp/portage/net-p2p/elements-23.2.1/work/elements-23.2.1/test/functional/feature_dbcrash.py", line 220, in run_test
    utxo_list = create_confirmed_utxos(self, self.nodes[3].getnetworkinfo()['relayfee'], self.nodes[3], 5000, sync_fun=self.no_op)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/net-p2p/elements-23.2.1/work/elements-23.2.1/test/functional/test_framework/util.py", line 525, in create_confirmed_utxos
    node.sendrawtransaction(signed_tx)
  File "/var/tmp/portage/net-p2p/elements-23.2.1/work/elements-23.2.1/test/functional/test_framework/coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/net-p2p/elements-23.2.1/work/elements-23.2.1/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: bad-txns-in-ne-out, value in != value out (-26)
2023-11-28T19:48:16.756000Z TestFramework (INFO): Stopping nodes
2023-11-28T19:48:17.219000Z TestFramework (WARNING): Not cleaning up dir /var/tmp/portage/net-p2p/elements-23.2.1/temp/test_runner_₿_🏃_20231128_144755/feature_dbcrash_254
2023-11-28T19:48:17.219000Z TestFramework (ERROR): Test failed. Test logging available at /var/tmp/portage/net-p2p/elements-23.2.1/temp/test_runner_₿_🏃_20231128_144755/feature_dbcrash_254/test_framework.log
2023-11-28T19:48:17.220000Z TestFramework (ERROR): 
2023-11-28T19:48:17.220000Z TestFramework (ERROR): Hint: Call /var/tmp/portage/net-p2p/elements-23.2.1/work/elements-23.2.1/test/functional/combine_logs.py '/var/tmp/portage/net-p2p/elements-23.2.1/temp/test_runner_₿_🏃_20231128_144755/feature_dbcrash_254' to consolidate all logs
2023-11-28T19:48:17.220000Z TestFramework (ERROR): 
2023-11-28T19:48:17.220000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-11-28T19:48:17.220000Z TestFramework (ERROR): https://github.com/ElementsProject/elements/issues
2023-11-28T19:48:17.221000Z TestFramework (ERROR): 


stderr:
```

**feature_dbcrash_254/node3/elementsregtest/debug.log**: 
[debug.log.gz](https://github.com/ElementsProject/elements/files/13492728/debug.log.gz)

**To reproduce**

```
$ ./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --datarootdir=/usr/share --disable-dependency-tracking --disable-silent-rules --disable-static --docdir=/usr/share/doc/elements-23.2.1 --htmldir=/usr/share/doc/elements-23.2.1/html --with-sysroot=/ --libdir=/usr/lib64 --disable-static --enable-wallet --with-sqlite --with-bdb --disable-usdt --without-miniupnpc --without-natpmp --enable-tests --disable-bench --disable-fuzz --disable-fuzz-binary --without-qrencode --disable-ccache --enable-asm --disable-zmq --enable-man --disable-external-signer --with-utils --enable-util-cli --enable-util-tx --enable-util-wallet --disable-util-util --without-seccomp --without-libs --with-daemon --without-gui --without-qtdbus --without-system-leveldb --with-system-libsecp256k1

$ make

$ /usr/bin/python3.12 test/functional/test_runner.py --ansi --extended --jobs=4 --timeout-factor=15
```

**System information**

Elements 23.2.1 source build

Gentoo Linux ~amd64

**Comment by delta1** [comment]
Hi @whitslack thanks for the feedback. It seems these tests are only run in the `extended` tests, which aren't run in CI since they take a very long time. I am busy with fixes for them. 

Cheers

**Comment by delta1** [comment]
Fixed in #1298
