### ISSUE TITLE
Send To Sidechain fails

### ISSUE THREAD

**Issue by poppingtonic** [ElementsProject/elements#30]
I've followed all the steps in `alpha-README.md`, but fail to see the expected result in Step 6 of `To Move Money into Elements Alpha`.

``` bash
$ ./contrib/sidechain-manipulation.py send-to-sidechain 2MuCWkMxPNLoV2qxCKXUSnmeZpz8VMtEzjz 1

Sending 1 to 2N82VPmsiZRC3xbDX9fxgiTKgkiY8BFjKZt...
(nonce: 4483e3dccfef99bc6e350a9665fc1ee5)

Traceback (most recent call last):
  File "./contrib/sidechain-manipulation.py", line 121, in <module>
    txid = bitcoin.sendtoaddress(send_address, Decimal(sys.argv[3]))
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 107, in __call__
    'id': self.__id_count})
  File "/usr/lib/python2.7/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 201, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python2.7/json/encoder.py", line 264, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python2.7/json/encoder.py", line 178, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Decimal('1') is not JSON serializable
```

**Comment by maaku** [comment]
You need to make Jeff Garzik's python-bitcoinrpc available on the python
path. There are two modules one which handles the Bitcoin side, and another
which handles the json-rpc, which you don't seem to have. the built-in
json-rpc won't work.
