### ISSUE TITLE
Insufficient priority when trying to claim-on-sidechain

### ISSUE THREAD

**Issue by gislik** [ElementsProject/elements#53]
While following the [steps](https://github.com/ElementsProject/elements/blob/alpha/alpha-README.md) to move money into Elements Alpha `sidechain-manipulation.py` throws an RPC-JSON exception:

> JSONRPCException: -26: 66: insufficient priority

Following is the transaction log of commands and replies:

```
# ./sidechain-manipulation.py generate-one-of-one-multisig sidechain-wallet
One-of-one address: 22E8QKHaTijFemPDwKvAk9qoTgagPfp8nBQiry87MMU1h2gQG78XZbxHedHgd6Gid57txjm3FdEcmqg85
P2SH address: 2Mz73R1ZUHPKrg3gCj5Z1X2woC3UiHh8asi

# ./sidechain-manipulation.py send-to-sidechain 2Mz73R1ZUHPKrg3gCj5Z1X2woC3UiHh8asi 1
Sending 1 to 2MsjEJu9KSsYPsRyHkx9ym7ALNhpX96Tf2Q...
(nonce: 90887ed8625cd48c00d101bb96b6a8b7)
Sent tx with id 24174c4d5981fb5f517f1a79b97586f850dad73e25439f1e2edf9fea0953c59f

# ./sidechain-manipulation.py claim-on-sidechain 2Mz73R1ZUHPKrg3gCj5Z1X2woC3UiHh8asi 90887ed8625cd48c00d101bb96b6a8b7 24174c4d5981fb5f517f1a79b97586f850dad73e25439f1e2edf9fea0953c59f
Redeeming from utxo bbcb5fc6e3c276409a6134fff59866db59f5b43b56601243b265d3dafc647a67:1 (value 20994185.69597788, refund 20994184.69597788)
Traceback (most recent call last):
  File "./sidechain-manipulation.py", line 195, in <module>
    txid = sidechain.sendrawtransaction(res_tx)
  File "/opt/elements/lib/python-bitcoinrpc/bitcoinrpc/authproxy.py", line 138, in __call__
    raise JSONRPCException(response['error'])
JSONRPCException: -26: 66: insufficient priority

Got the following error from an RPC Call:
{u'message': u'66: insufficient priority', u'code': -26}
```

I have tried multiple times, initially I didn't have any `alphatestnet3` coins but since then I have some from the faucet.

```
# ./alpha-cli.sh getwalletinfo
{
    "walletversion" : 60000,
    "balance" : 1.00000000,
    "txcount" : 1,
    "keypoololdest" : 1442243484,
    "keypoolsize" : 98,
    "unlocked_until" : 0
}
```

Then I thought the amount I was trying to send was too small (I was using 0.4 `testnet3` coins but the manual was using 1.0) but my last attempt using 1.0 yielded the same exception.

I'm running the `alphad` daemon with the following configuration:

```
testnet=1
rpcuser=elements_user
rpcpassword=elements_pass
rpcconnect=127.0.0.1
rpcconnectport=18332
tracksidechain=all
txindex=1
#blindtrust=true
```

and `bitcoind` daemon with:

```
testnet=1
rpcuser=elements_user
rpcpassword=elements_pass
txindex=1
```
The source code is in sync with `HEAD` on GitHub. 

I'm very interested in the project and happy to provide further details if needed.

**Comment by amiller** [comment]
I also am stuck on the same error, under the same circumstances:
https://gist.github.com/amiller/e86fa22502e54c10678d
I'm on ubuntu 14.04.

**Comment by pstratem** [comment]
try setting relaypriority=0
