### ISSUE TITLE
feature_pak.py intermittant failure when restarting nodes

### ISSUE THREAD

**Issue by instagibbs** [ElementsProject/elements#576]
Running the test on a spin-loop I get this error:

```
2019-04-12T18:53:37.035000Z TestFramework (INFO): Stopping nodes
2019-04-12T18:53:37.345000Z TestFramework (INFO): Cleaning up /tmp/test_a726e63 on exit
2019-04-12T18:53:37.345000Z TestFramework (INFO): Tests successful
2019-04-12T18:53:37.501000Z TestFramework (INFO): Initializing test directory /tmp/testezoh_vcg
2019-04-12T18:53:48.064000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_framework.py", line 326, in start_nodes
    node.wait_for_rpc_connection()
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_node.py", line 178, in wait_for_rpc_connection
    'bitcoind exited with status {} during initialization'.format(self.process.returncode)))
test_framework.test_node.FailedToStartError: [node 1] bitcoind exited with status 1 during initialization

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_framework.py", line 171, in main
    self.run_test()
  File "./test/functional/feature_pak.py", line 376, in run_test
    self.start_nodes(extra_args)
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_framework.py", line 329, in start_nodes
    self.stop_nodes()
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_framework.py", line 345, in stop_nodes
    node.stop_node()
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_node.py", line 213, in stop_node
    self.stop()
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_node.py", line 142, in __getattr__
    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")
AssertionError: [node 1] Error: no RPC connection
2019-04-12T18:53:48.117000Z TestFramework (INFO): Stopping nodes
Traceback (most recent call last):
  File "./test/functional/feature_pak.py", line 414, in <module>
    PAKTest ().main ()
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_framework.py", line 196, in main
    self.stop_nodes()
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_framework.py", line 345, in stop_nodes
    node.stop_node()
  File "/home/instagibbs/elements-dev/elements/test/functional/test_framework/test_node.py", line 218, in stop_node
    self.stderr.seek(0)
  File "/usr/lib/python3.5/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
ValueError: seek of closed file
[node 4] Cleaning up leftover process
[node 3] Cleaning up leftover process
[node 2] Cleaning up leftover process
[node 1] Cleaning up leftover process
[node 0] Cleaning up leftover process
```
money shot being:
```
  File "./test/functional/feature_pak.py", line 376, in run_test
    self.start_nodes(extra_args)
```
And the corresponding suspicious logs for node 1:

```
2019-04-12T18:53:47.630848Z BerkeleyEnvironment::Flush: wallet.dat checkpoint
2019-04-12T18:53:47.631737Z BerkeleyEnvironment::Flush: wallet.dat detach
2019-04-12T18:53:47.633035Z BerkeleyEnvironment::Flush: wallet.dat closed
2019-04-12T18:53:47.633058Z BerkeleyEnvironment::Flush: Flush(true) took               4ms
2019-04-12T18:53:47.639727Z [default wallet] Releasing wallet
2019-04-12T18:53:47.639873Z Shutdown: done
2019-04-12T18:53:47Z 




2019-04-12T18:53:47.861727Z Elements Core version v0.17.0.0-1fdc059 (release build)
2019-04-12T18:53:47.861737Z InitParameterInteraction: parameter interaction: -bind set -> setting -listen=1
2019-04-12T18:53:47.861753Z InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2019-04-12T18:53:47.861804Z Validating signatures for all blocks.
2019-04-12T18:53:47.861812Z Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000000000000000
2019-04-12T18:53:47.861908Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
2019-04-12T18:53:47.861914Z Using RdRand as an additional entropy source
2019-04-12T18:53:47.875639Z Default data directory /home/instagibbs/.elements
2019-04-12T18:53:47.875646Z Using data directory /tmp/testezoh_vcg/node1/regtest2
2019-04-12T18:53:47.875655Z Config file: /tmp/testezoh_vcg/node1/elements.conf
2019-04-12T18:53:47.875659Z Using at most 125 automatic connections (1024 file descriptors available)
2019-04-12T18:53:47.882354Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2019-04-12T18:53:47.888733Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2019-04-12T18:53:47.901800Z Using 32 MiB out of 32 requested for rangeproof cache, able to store 1048576 elements
2019-04-12T18:53:47.914847Z Using 32 MiB out of 32 requested for surjectionproof cache, able to store 1048576 elements
2019-04-12T18:53:47.914862Z Using 8 threads for script verification
2019-04-12T18:53:47.915089Z scheduler thread start
2019-04-12T18:53:47.915233Z Allowing HTTP connections from: 127.0.0.0/8 ::1/128 
2019-04-12T18:53:47.915289Z Binding RPC on address ::1 port 20316
2019-04-12T18:53:47.915361Z Binding RPC on address ::1 port 20316 failed.
2019-04-12T18:53:47.915367Z Binding RPC on address 127.0.0.1 port 20316
2019-04-12T18:53:47.915394Z Binding RPC on address 127.0.0.1 port 20316 failed.
2019-04-12T18:53:47.915399Z Unable to bind any endpoint for RPC server
2019-04-12T18:53:47.915415Z Error: Unable to start HTTP server. See debug log for details.
2019-04-12T18:53:47.915434Z Interrupting HTTP server
2019-04-12T18:53:47.915438Z Interrupting HTTP RPC server
2019-04-12T18:53:47.915443Z Interrupting RPC
2019-04-12T18:53:47.915448Z Shutdown: In progress...
2019-04-12T18:53:47.915454Z Stopping HTTP RPC server
```

**Comment by instagibbs** [comment]
haven't seen this lately. Closing for now.
