### ISSUE TITLE
Issue on claim-on-sidechain in sidechain-manipulation.py

### ISSUE THREAD

**Issue by AccentureTechLabs** [ElementsProject/elements#83]
Hi,

I was trying to testing the sidechain, but there was a problem when I called the function claim-on sidechain, here is the details:

`Redeeming from utxo 4a466058a8754698a95ff29bc8bece97e1e131dfda29f76d30c958903fd85eb0:1 (value 20994180.93597788, refund 20994180.43597788)
[libsecp256k1] illegal argument: *outputlen >= ((flags & SECP256K1_FLAGS_BIT_COMPRESSION) ? 33 : 65)
Traceback (most recent call last):
  File "./contrib/sidechain-manipulation.py", line 237, in <module>
    txid = sidechain.sendrawtransaction(res_tx)
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 139, in __call__
    response = self._get_response()
  File "/usr/local/lib/python2.7/dist-packages/bitcoinrpc/authproxy.py", line 180, in _get_response
    http_response = self.__conn.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1045, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 409, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 373, in _read_status
    raise BadStatusLine(line)
httplib.BadStatusLine: ''`

Additionally, I just checked the log of alpha, and it says:

`2016-02-15 13:47:48 opencon thread start
2016-02-15 13:47:48 addcon thread start
2016-02-15 13:47:48 net thread start
2016-02-15 13:47:48 dnsseed thread start
2016-02-15 13:47:49 receive version message: /ElementsAlpha:0.10.2/: version 70002, blocks=128650, us=170.252.244.1:37198, peer=1
2016-02-15 13:47:49 Added time data, samples 2, offset +0 (+0 minutes)
2016-02-15 13:47:50 receive version message: /ElementsAlpha:0.10.2/: version 70002, blocks=128650, us=170.252.244.1:56955, peer=2
2016-02-15 13:47:50 Added time data, samples 3, offset +0 (+0 minutes)
2016-02-15 13:47:51 Cannot connect to i6gawycbsddduuvp.onion:4242: unsupported network
2016-02-15 13:47:53 Cannot connect to 4azvkpo55qaskhjl.onion:4242: unsupported network
2016-02-15 13:47:56 Cannot connect to 4zhkir2ofl7orfom.onion:4242: unsupported network
2016-02-15 13:47:57 connect() to [2604:a880:1:20::269:c001]:4242 failed: Network is unreachable (101)
2016-02-15 13:47:58 connect() to [2600:3c00::f03c:91ff:fe98:986]:4242 failed: Network is unreachable (101)
2016-02-15 13:47:59 Cannot connect to jojqfliinm4prlo4.onion:4242: unsupported network
2016-02-15 13:47:59 P2P peers available. Skipped DNS seeding.
2016-02-15 13:47:59 dnsseed thread exit
2016-02-15 13:48:00 Cannot connect to bbgw7gpjpko5yvuh.onion:4242: unsupported network
2016-02-15 13:48:02 connect() to 45.56.122.234:4242 failed after select(): Connection refused (111)
2016-02-15 13:48:02 connect() to 50.0.37.37:4242 failed after select(): No route to host (113)
`

I don't know if the connection issue may affect the claiming process?
I have tried also different version of libsecp256k1 and contracthashtool, mention in #59, but it didn't help either.
Do you have some suggestions on this?

Thank you,

**Comment by instagibbs** [comment]
For the first issue the newest version of elements should have this fixed. https://github.com/ElementsProject/elements/issues/79

https://github.com/Blockstream/contracthashtool/pull/8/files?diff=split  

It was merged 5 days ago.  

re:connections, what does getpeerinfo tell you?

**Comment by AccentureTechLabs** [comment]
Hi instagibbs,

I have pulled the latest contracthastool to the newest version, but the error still remained. I've tried both libsecp from ElementsProject and from the the libsecp github site. Do I need to do send to sidechain another btc to claim it? I kept the alphatestnet3 the same, did not remove the wallet.dat in it.

Here is the info when I typed alpha-cli getpeerinfo

`[
    {
        "id" : 1,
        "addr" : "162.243.132.6:4242",
        "addrlocal" : "170.252.244.1:62213",
        "services" : "0000000000000001",
        "lastsend" : 1455547061,
        "lastrecv" : 1455547064,
        "bytessent" : 1925,
        "bytesrecv" : 2291,
        "conntime" : 1455547060,
        "pingtime" : 0.44494400,
        "version" : 70002,
        "subver" : "/ElementsAlpha:0.10.2/",
        "inbound" : false,
        "startingheight" : 128650,
        "banscore" : 0,
        "synced_headers" : 128650,
        "synced_blocks" : 128650,
        "inflight" : [
        ],
        "whitelisted" : false
    },
    {
        "id" : 2,
        "addr" : "104.236.132.224:4242",
        "addrlocal" : "170.252.244.1:57671",
        "services" : "0000000000000001",
        "lastsend" : 1455547063,
        "lastrecv" : 1455547064,
        "bytessent" : 1925,
        "bytesrecv" : 2711,
        "conntime" : 1455547063,
        "pingtime" : 0.45263300,
        "version" : 70002,
        "subver" : "/ElementsAlpha:0.10.2/",
        "inbound" : false,
        "startingheight" : 128650,
        "banscore" : 0,
        "synced_headers" : 128650,
        "synced_blocks" : 128650,
        "inflight" : [
        ],
        "whitelisted" : false
    }
]
`

**Comment by instagibbs** [comment]
It actually looks like an error is occurring inside alphad itself during the sendrawtransaction call.

**Comment by TomMcCabe** [comment]
I'm also getting the same error when trying to `claim-on-sidechain`. I'm trying to build a different sidechain and create the documentation for other users as the current instructions are not clear. I've changed the port numbers in constants.py and chainparamsbase.cpp (essentially just replacing 4241 with 4242). I've rebuilt both alphad and bitcoind after editing cpp files. If I run `getpeerinfo` I also return the same result with my local ip in `addrlocal`. It fails at the `txid = sidechain.sendrawtransaction(res_tx)` line, but I think it is because there's a communication error with the ports.

**Comment by instagibbs** [comment]
Ok we've found the issue:  
https://github.com/ElementsProject/elements/blob/alpha/src/script/interpreter.cpp#L1469  

Same issue but in alpha instead post-libsecp update. Fix incoming.

**Comment by instagibbs** [comment]
Try this: https://github.com/ElementsProject/elements/pull/84

**Comment by AccentureTechLabs** [comment]
@instagibbs 
It works now with the claim-on-sidechain call.
I will try with other calls and let you know.
Huge thanks!
